# Generated by Django 4.2.13 on 2024-05-25 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0002_remove_userprofile_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validation',
            name='user_profile',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='validation', to='myproject.userprofile'),
        ),
    ]
