# Generated by Django 4.2.13 on 2024-06-09 14:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myproject', '0004_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='accuracy',
        ),
        migrations.RemoveField(
            model_name='company',
            name='risk',
        ),
        migrations.RemoveField(
            model_name='company',
            name='score',
        ),
        migrations.RemoveField(
            model_name='company',
            name='summary',
        ),
        migrations.AddField(
            model_name='company',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='companies', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('accuracy', models.FloatField()),
                ('risk', models.FloatField()),
                ('summary', models.TextField()),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='myproject.company')),
            ],
        ),
    ]
