# Generated by Django 4.2.13 on 2024-06-10 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0005_remove_company_accuracy_remove_company_risk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='document_status',
            field=models.CharField(default='Not Uploaded', max_length=50),
        ),
    ]
